[package]
name = "dilate"
version = "0.3.0"
edition = "2021"
license-file = "Anti-Capitalist Software License (v 1.4)"
description = "A compact, high performance integer dilation library for Rust."
homepage = "https://github.com/alexmadeathing/dilate"
repository = "https://github.com/alexmadeathing/dilate"
documentation = "https://docs.rs/dilate"
readme = "README.md"
categories = ["algorithms", "encoding"]
keywords = ["morton", "integer", "dilate", "dilation", "octree"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
serde = { version = "1.0.136", features = ["derive"] } # For test data serialisation
serde_json = "1.0.78" # For test data serialisation
lazy_static = "1.4.0" # For test data serialisation
paste = "1.0.6" # For generation of multi-dimensional, multi-type, tests
